### ISSUE TITLE
Compilation task.json addition

### ISSUE THREAD

**Issue by MNSleeper** [popbr/data-integration#10]
@aubertc , Would it be possible to add either:
mvn compile
or
mvn exec:java -Dexec.mainClass="com.mycompany.app.App"
to the tasks.json "tasks.args" section to make compiling/building the program easier? I only ask because I did something similar to another project of mine that needed extra build arguments, and that worked.

If it helps, I was usings Windows winsock2 (for a client/server model) and it needed "-1Ws2_32" in the compile line to properly compile it. Once I added it to the task.json "tasks" section, it compiled fine.

**Comment by aubertc** [comment]
I am not familiar with those technologies, but sure, why not.

**Comment by aubertc** [comment]
Or you are asking me to do it?

**Comment by MNSleeper** [comment]
I was asking if you knew if it would work/had any experience with trying something like this. I'll try it out.

**Comment by aubertc** [comment]
I have no experience with this tool.

**Comment by aubertc** [comment]
I am not sure I understand the original issue or why you closed it. If this tool had a purpose and simplified something for you, then yes, we should try to use it.

**Comment by MNSleeper** [comment]
Oh, my apologies. It's not a tool, it's a file that vscode uses to compile a project with additional parameters. It doesn't seem like something that that will work with Maven, though. I attached the tasks.json file of a project I mentioned in the example for clarity on what it is. Perhaps this will help clear up any confusion.
[tasks.txt.txt](https://github.com/popbr/data-integration/files/9841544/tasks.txt.txt)

**Comment by aubertc** [comment]
If it's a VS feature, there is no harm in adding it, simply indicate somewhere that it is provided as a courtesy to the users of this tool.

**Comment by aubertc** [comment]
Sure, please go ahead.
