### ISSUE TITLE
Making the installation test executes succesfully on github

### ISSUE THREAD

**Issue by aubertc** [popbr/data-integration#14]
The [current Java_CI.yml](https://github.com/popbr/data-integration/blob/main/.github/workflows/Java_CI.yml) is successful in compiling the test.

However, it cannot be successfully executed, cf. https://github.com/popbr/data-integration/actions/runs/3316925417/jobs/5479254033#step:4:8119 

_Follow-up from https://github.com/popbr/data-integration/issues/5#issuecomment-1289779987_

**Comment by MNSleeper** [comment]
How do we solve this? Is there some SQL plugin for Git we can use?

**Comment by aubertc** [comment]
I can investigate. [This file](https://github.com/popbr/data-integration/blob/main/.github/workflows/main.yml) contains the initial set-up for mysql, but I may have mis-configured it.

**Comment by aubertc** [comment]
Ok, the installation can be compiled and executed again, but there is still something off with the communication with the mysql server, cf. https://github.com/popbr/data-integration/actions/runs/3398128249/jobs/5650903711#step:4:8144

**Comment by aubertc** [comment]
Ok, the [test now works](https://github.com/popbr/data-integration/actions/runs/3398246569/jobs/5651128100#step:5:36), and we can [download the resulting artifact](https://github.com/popbr/data-integration/suites/9141237666/artifacts/424888201).

In this case, this is "simply" the test spreadsheet, but in the future we should be able to get back from github the spreadsheet resulting from the actual program run.
