### ISSUE TITLE
Installation_Test Workflow

### ISSUE THREAD

**Issue by KingAdam2004** [popbr/data-integration#28]
Currently, the workflow is ran every single time a push is made to the repository. However, we want it to only run when we make changes to the source code. To accomplish this, we need to:

- Make changes to the workflow to only run when a push is made to the *data-integration\Installation_Test\src\main\java\popbr\InstallationTest.java* file. 

In addition to this, we also want to:

- Add better documentation to the workflow so that we know exactly what is happening with our saved artifact.
- Add a better name to the saved artifact.

**Comment by aubertc** [comment]
This was taken care of with https://github.com/popbr/data-integration/commit/b0d042d4f00b465bfe09abe51d4c3c55ccca918c
