### ISSUE TITLE
Confirm that project compile

### ISSUE THREAD

**Issue by aubertc** [popbr/data-integration#5]
Since [my last commits](https://github.com/popbr/data-integration/commit/225f77d6faf18c53595e435b910a51da67d07b5e), I can compile the project just fine.
However, it seems that github cannot, [returning the error message](https://github.com/popbr/data-integration/actions/runs/3131086588/jobs/5082058645) 

> Error:  Failed to execute goal org.codehaus.mojo:exec-maven-plugin:3.1.0:java (default-cli) on project Installation_Test: An exception occurred while executing the Java class. Provider org.apache.xerces.jaxp.DocumentBuilderFactoryImpl not found -> [Help 1]

Can you confirm that it compiles on your end, @MNSleeper , and / or try to get github to compile it properly?

**Comment by MNSleeper** [comment]
Project does compile. I have had to comment out website scraping methods, as they aren't fully implemented and don't work. I see now I have to move them to their own mini java file and work on it until it, well, works. For now, they're commented out and the program compiles for me.

**Comment by aubertc** [comment]
Start by looking at
https://github.com/popbr/data-integration/actions/runs/3286988349/jobs/5415676634#step:4:6956
I am not sure what it is complaining about, maybe we have some configuration wrong.

**Comment by aubertc** [comment]
Commenting further on that:

- Github now uses Java 17 since https://github.com/popbr/data-integration/commit/b650be8f64e76386f5f6194e27d47c12677b48b2
- Observe that we are simply trying to complete the Installation-test:
https://github.com/popbr/data-integration/blob/b650be8f64e76386f5f6194e27d47c12677b48b2/.github/workflows/Java_CI.yml#L18
- The [errors](https://github.com/popbr/data-integration/actions/runs/3298433024/jobs/5440543721#step:4:6936) are 
```
Error:  /home/runner/work/data-integration/data-integration/Installation_Test/src/main/java/com/mycompany/app/App.java:[51,96] 'void' type not allowed here
Error:  /home/runner/work/data-integration/data-integration/Installation_Test/src/main/java/com/mycompany/app/App.java:[259,13] cannot find symbol
  symbol:   variable result
  location: class com.mycompany.app.App
Error:  /home/runner/work/data-integration/data-integration/Installation_Test/src/main/java/com/mycompany/app/App.java:[262,13] cannot find symbol
  symbol:   variable result
  location: class com.mycompany.app.App
Error:  /home/runner/work/data-integration/data-integration/Installation_Test/src/main/java/com/mycompany/app/App.java:[265,16] incompatible types: unexpected return value
Error:  /home/runner/work/data-integration/data-integration/Installation_Test/src/main/java/com/mycompany/app/App.java:[289,13] cannot find symbol
  symbol:   variable result
  location: class com.mycompany.app.App
Error:  /home/runner/work/data-integration/data-integration/Installation_Test/src/main/java/com/mycompany/app/App.java:[292,16] cannot find symbol
  symbol:   variable result
  location: class com.mycompany.app.App
Error:  /home/runner/work/data-integration/data-integration/Installation_Test/src/main/java/com/mycompany/app/App.java:[332,24] cannot find symbol
```
- So, the first one is about this line: https://github.com/popbr/data-integration/blob/main/Installation_Test/src/main/java/com/mycompany/app/App.java#L51

Note that I have the same error on my installation.

**Comment by MNSleeper** [comment]
I found a few errors that prevented compilation and fixed them. For me,I can compile Installation Test now

**Comment by aubertc** [comment]
Please, don't hesitate to [add links](https://github.com/popbr/data-integration/actions/runs/3301128682/jobs/5446280194#step:4:7991) to the error messages.

[It seems](https://stackoverflow.com/a/15265458) that adding

```
<dependency>
    <groupId>xerces</groupId>
    <artifactId>xercesImpl</artifactId>
    <version>2.12.2</version>
</dependency>
```

(the version may not be the "right" one) to [the pom](https://github.com/popbr/data-integration/blob/main/Installation_Test/pom.xml) could solve that.

**Comment by MNSleeper** [comment]
Should this be added to both the DatabaseIO Project as well?

**Comment by aubertc** [comment]
Ok, so the [current Java_CI.yml](https://github.com/popbr/data-integration/blob/main/.github/workflows/Java_CI.yml) "works" for the test, that's good to know.
"Works" in the sens that the project can be compiled, but the execution does _not_ succeed, cf. https://github.com/popbr/data-integration/actions/runs/3316925417/jobs/5479254033#step:4:8119 

This may (or may not) be the next issue we want to tackle: how to make this program executes successfully on github's servers?

**Comment by MNSleeper** [comment]
After Matching, the next big issue is Scraping, then Git Execution

**Comment by aubertc** [comment]
We can close this issue for now, then.
